### ISSUE TITLE
joystick.service  error

### ISSUE THREAD

**Issue by LittleBookboy12138** [stanfordroboticsclub/StanfordQuadruped#20]
Both joystick.service and robot.service  are active, but an error occurred while connecting the PS4 to the Pupper.

The specific questions are as follows:
pi@raspberrypi(rw):~$ sudo systemctl status joystick.service 
● joystick.service - Pupper Joystick service
   Loaded: loaded (/boot/appliance/home/pi/PupperCommand/joystick.service; enabl
   Active: activating (auto-restart) (Result: exit-code) since Thu 2019-02-14 10
  Process: 525 ExecStart=/usr/bin/python3 /home/pi/PupperCommand/joystick.py (co
 Main PID: 525 (code=exited, status=1/FAILURE)

**Comment by gowitty** [comment]
https://github.com/stanfordroboticsclub/UDPComms
DEFAULT_IP = "10.0.0.255"

ip By default UDPComms sends to the 10.0.0.X subnet, but can be changed to a different ip using this argument. 
Set to localhost (127.0.0.1) for development on the same computer.

**Comment by marx-bryan** [comment]
![S $~8Y4L5TJJYB`Y$ X~F4R](https://user-images.githubusercontent.com/83152729/159105296-8bc02f08-d100-4262-b621-b21494faf4ff.png)
i have the same question ,still unsolved

**Comment by mikh3x4** [comment]
try running `python3 /home/pi/PupperCommand/joystick.py` to run the joystick program without systemd. What does it output?

**Comment by marx-bryan** [comment]
> try running `python3 /home/pi/PupperCommand/joystick.py` to run the joystick program without systemd. What does it output?

pi@pi(rw):~/PupperCommand$ sudo python3 joystick.py
Can't get device info: No such device
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/ds4drv/backends/bluetooth.py", line 89, in setup
    subprocess.check_output(["hcitool", "clock"],
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['hcitool', 'clock']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/PupperCommand/joystick.py", line 14, in <module>
    joystick = Joystick()
  File "/usr/local/lib/python3.9/dist-packages/PS4Joystick.py", line 85, in __init__
    backend.setup()
  File "/usr/local/lib/python3.9/dist-packages/ds4drv/backends/bluetooth.py", line 92, in setup
    raise BackendError("'hcitool clock' returned error. Make sure "
ds4drv.exceptions.BackendError: 'hcitool clock' returned error. Make sure your bluetooth device is powered up with 'hciconfig hciX up'.

**Comment by mikh3x4** [comment]
have you tired running `hciconfig hciX up` before running that command? Its a bit weird because I think joystick.py should run that on its own but I want to make sure

**Comment by marx-bryan** [comment]
sudo hciconfig hciX up
Can't get device info: No such device

**Comment by marx-bryan** [comment]
To start with,I didnt use offical img ,instead i used version _2021 bulleyes( 2021-10-30-raspios-bullseye),and followed the offical document to install the software

**Comment by mikh3x4** [comment]
It seems like the pi's bluetooth module is not showing up at all. What version of Pi are you using? What's the output of `hcitool dev`?

**Comment by marx-bryan** [comment]
raspberry 4b ,pi@pi(rw):~/PupperCommand$ hcitool dev
Devices:
device is blank

**Comment by mikh3x4** [comment]
It's possible something changed between raspios versions. A quick googling brings [this](https://forums.raspberrypi.com/viewtopic.php?t=323228) up which suggests early bullseye versions had something wrong with bluetooth. I would recommend updating raspios (it should be possible to do in place without reinstalling) and seeing if that fixes things

**Comment by marx-bryan** [comment]
pi@pi(rw):~$ sudo nano /etc/apt/sources.list.d/raspi.list
pi@pi(rw):~$ sudo apt-get update
Hit:1 http://mirrors.tuna.tsinghua.edu.cn/raspbian/raspbian bullseye InRelease
Hit:2 http://mirrors.tuna.tsinghua.edu.cn/raspberrypi bullseye InRelease
Reading package lists... Done
pi@pi(rw):~$ sudo apt-get upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@pi(rw):~$ sudo hcitool dev
Devices:
still blank
i think maybe i need to reinstall it to the newest version

**Comment by marx-bryan** [comment]
> It's possible something changed between raspios versions. A quick googling brings [this](https://forums.raspberrypi.com/viewtopic.php?t=323228) up which suggests early bullseye versions had something wrong with bluetooth. I would recommend updating raspios (it should be possible to do in place without reinstalling) and seeing if that fixes things

thanks for your advice

**Comment by AlfredMoore** [comment]
> pi@pi(rw):~$ sudo nano /etc/apt/sources.list.d/raspi.list pi@pi(rw):~$ sudo apt-get update Hit:1 http://mirrors.tuna.tsinghua.edu.cn/raspbian/raspbian bullseye InRelease Hit:2 http://mirrors.tuna.tsinghua.edu.cn/raspberrypi bullseye InRelease Reading package lists... Done pi@pi(rw):~$ sudo apt-get upgrade Reading package lists... Done Building dependency tree... Done Reading state information... Done Calculating upgrade... Done 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded. pi@pi(rw):~$ sudo hcitool dev Devices: still blank i think maybe i need to reinstall it to the newest version

Did you solve it ? Totally same problem, though I am in the Debian 10.
